### ISSUE TITLE
Intermittent issue with kubeapply

### ISSUE THREAD

**Issue by LukeShu** [datawire/teleproxy#41]
I'd gotten this crash https://circleci.com/gh/datawire/teleproxy/442 and re-running made it go away.

**Comment by LukeShu** [comment]
Still present in 0.3.8

**Comment by rhs** [comment]
I believe this should be fixed now in 0.3.10 or later thanks to @LukeShu's sage advice. If this crops up in a later version, please reopen (or file a new issue).
